# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c02f325b00d0dbefb62be6580b305e928ca49510bc32f22190ee8244a2a43bdb227bbaf080d1346cb2b8477720fcc4e507a1b145bc389ff7bf47bea0a6e8c7b

test:
  secret_key_base: a07abd8bc3ea670322914978e02ad2557d66b547a7a557682e2d91ad656c90749fba9d9bd184d87376dd63aea477e38f5f509c8df4f001c541ec0c45c9ac0177

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
